# fly.toml app configuration file for hominio-wallet
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'hominio-wallet'
primary_region = 'fra'

[build]

[env]
PORT = '3000'
NODE_ENV = 'production'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1  # Keep at least 1 machine running for auth service availability
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

